language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install coverage==3.7.1
  - pip install tornado
  - pip install coveralls
  - pip install mecab-python3 unidic-lite

script:
  - PYTHONPATH=.:$PYTHONPATH coverage run --source=mrep,scripts setup.py test

after_success:
  - coveralls
